# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
    ]
